services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  
  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    ports:
      - "5000:5000"